### ISSUE TITLE
Definir o escopo do projeto

### ISSUE THREAD

**Issue by lucasppimentel** [lucasppimentel/termometro-eleicoes#1]
A ideia dessa issue é formalizar a discussão do que cada um de nós espera desse projeto. Quais são as ideias que vão nortear o nosso desenvolvimento e o produto final.

Podemos iniciar a discussão respondendo algumas perguntas fundamentais. Marquei algumas abaixo, mas não é um lista exaustiva.
1. Qual é a premissa do projeto?
2. Deve ser um projeto sério?
3. O que queremos que os usuários vejam / sintam ao acessar o projeto?

**Comment by lucasppimentel** [comment]
O que motivou o projeto?
-
A ideia do projeto surgiu do sentimento de que as pessoas não tem visibilidade total das estratégias que os candidatos usam durante as eleições, e muitas vezes não percebem que alguns candidatos apresentam poucas propostas ou um plano raso, mal feito ou incompleto para seu mandato.

Minha tese é de que essa falta de visibilidade acontece porque no período de eleições surge um fluxo de informações muito grande, de muitas fontes ao mesmo tempo, que torna muito difícil acompanhar do começo ao fim todas as propostas, falas e projetos dos candidatos.

O que os usuários deveriam ver / sentir?
-
A grande vantagem desse projeto é que é muito fácil gerar emoções quando o assunto são eleições. Acho que deveríamos tentar gerar um choque nos usuários, mostrando claramente quais foram as estratégias dos candidatos, quais usaram mais provocações, quais focaram em propostas, quais tiveram as propostas mais realistas e quais atacaram mais / foram mais atacados por outros candidatos.

O que eu espero do projeto
-
Não acho que deve ser um projeto 100% sério, desses que são quase _sombrios_, até porque isso não viraliza. Para gerar um choque no público mais geral, acho que podemos disfarçar as informações com uma roupa de meme. Acho que seria legal termos um ranking do candidato mais fanfarrão, quem fala mais groselha, quem é o saco de pancadas, e por aí vai.

Depois das piadas, dá para colocar algumas análises mais aprofundadas numa segunda camada, pro usuário que estiver disposto a ler além da primeira página.

**Comment by joaovcdc** [comment]
### O que me motivou em participar
Quando escutei essa ideia de projeto, achei muito divertido, sinto que cai de paraquedas em um projeto sério, mas como você disse, não precisa ser 100% sério. O que mais me motiva em um projeto como esse, acredito, é o processo de construção, desde a organização até a execução, além de mostrar para o eleitor um outro lado, de como os canditados se saem em debates de acordo com alguma métrica que vamos criar.

### O que eu espero do projeto
Espero poder contribuir para trazer uma abordagem diferente aos debates. O Brasil é muito bom em criar memes, e criar algo assim seria muito legal. Mal posso esperar para ver um tipo de "pipocômetro" em ação!
