### ISSUE TITLE
Definir o nome do site

### ISSUE THREAD

**Issue by joaovcdc** [lucasppimentel/termometro-eleicoes#2]

**Comment by lucasppimentel** [comment]
Pensei aqui em uma ideia, me fala se faz sentido.

Quando alguém não aguenta a pressão ou foge de alguma pergunta a gente fala que ele pipocou.
E se a gente chamar de _medidor de pipocas_, como quem não quer nada, e daí medir o desempenho dos candidatos com uma nota que vai de _pipoca_ (nota 0) até _milho_ (nota 10)? Igual no _rotten tomatoes_, que vai de tomate fresco até tomate estragado.

Algumas variações:

1. Medidor de pipocas
2. Pipocômetro
3. Pipocômetro eleitoral

**Comment by joaovcdc** [comment]
Sensacional, gostei muito da referência, não conhecia o "Rotten Tomatoes", curti muito a ideia de como medir o desempenho, podemos seguir como você mencionou. Agora, sobre as variações de nome que você mencionou, gostei muito da opção n°3 e n°2, mas curti mais a n°3. Se eu tiver alguma ideia pra nome (que seja criativa), sugiro por aqui.

**Comment by lucasppimentel** [comment]
Bem demais kkkkk, a gente pode seguir com a 3 então, por enquanto pelo menos

**Comment by joaovcdc** [comment]
Combinado, vou encerrar essa issue então. E é claro que nada impedi de mudarmos depois, como você mesmo disse.
