### ISSUE TITLE
Discussão: Quais tecnologias vamos usar?

### ISSUE THREAD

**Issue by lucasppimentel** [lucasppimentel/termometro-eleicoes#3]

**Comment by joaovcdc** [comment]
### Tecnológias Utilizadas 
Discussão de quais linguagens e tecnológias vão ser utilizadas para construção da página. 
1 - Quais linguagens podemos utilizar
2 - Hospedagem do site
3 - Outras considerações importantes (se necessário)

**Comment by joaovcdc** [comment]
### 1. Quais linguagens podemos utilizar
Particularmente, não tenho experiência na construção de páginas, exceto por um pouco de prática com Python utilizando a biblioteca Streamlit, que é fácil de usar, mas apresenta algumas limitações. Acredito que utilizar outro tipo de linguagem seria mais recomendado para o nosso caso. Se tiver alguma sugestão de linguagem, fique a vontade.

### 2. Hospedagem do Site
Pesquisei aqui e algumas recomendações gratuitas foram:
1 - Vercel
2 - Render 
3 - Heroku
Vi que o vercel é super simples de se utilizar: https://www.youtube.com/watch?v=e7L_8XVQBik&ab_channel=EvertonDev
Não fui tão afundo nas outras duas opções, mas se for melhor utilizar uma outra opção, comente aí

**Comment by lucasppimentel** [comment]
Acho bom usar Vercel pra hospedagem. Sobre nossa stack, pensei em:

Stack do projeto
-
- Front-end: `next.js`
Framework para desenvolvimento React. Prefiro next porque é o que estou estudando agora.

- Back-end: `Python`
Acho que esse projeto vai caminhar rápido pro lado de machine learning, fico mais confortável em construir o back-end e a API em Python pra trabalhar dessa forma com dados.

- Hospedagem: `Vercel`
Já usei a plataforma, concordo que vai satisfazer o que a gente precisa.

- Banco de dados: `PostgreSQL`
**[Motivo resumido]** Open source, baixo custo, fácil de usar e vai suprir nossa demanda por um bom tempo. Tenho uma discussão maior abaixo sobre essa questão do banco de dados.

> **[Motivo completo]** Ainda não tenho certeza sobre nosso banco de dados, essa resposta depende de como o nosso site vai se comportar. Por exemplo, se a gente escolher criar uma feature para o usuário inputar o link de um debate e receber as estatísticas, nosso servidor terá que:
> 1. [Via API] Obter a transcrição do vídeo (vai ser um texto bem longo)
> 2. [Via API] Separar as falas de cada candidato
> 3. [Via API] Classificar as falas
> 4. Calcular métricas de cada candidato
> 5. Retornar informações
> Nesse fluxo, temos poucas informações armazenadas no nosso banco de dados, uma vez que o fluxo todo é concluído e nada fica armazenado no site depois que as informações são retornadas. Nesse caso acho que um banco de dados `PostgreSQL` seria mais do que o suficiente.
> 
> Mas se quisermos coletar informações e calcular nossas métricas em massa, usando crawlers / webscrappers, por exemplo, e apenas disponibilizar essas informações aos usuários, pode ser interessante usarmos também um sistema de arquivos (`data lake`) para armazenar também os textos, áudios ou até imagens/vídeos coletados.
> 
> Eu queria avançar o projeto para essa visão de coleta em maior escala. A dificuldade aumenta muito, mas acho um exercício mais legal. 
> Mas em geral, acho que podemos usar um `PostgreSQL` pra iniciar o projeto e manter o pé no chão por enquanto.

Testes e ambiente
-
Pegando o gancho, podemos usar ainda:
- Testes automatizados: `jest`
- Línter: `prettier`

**Comment by lucasppimentel** [comment]
A discussão aqui foi pro lado de tecnologia haha. Vou mudar o título dessa issue.

**Comment by joaovcdc** [comment]
Fechou, vamos seguir dessa forma! Estou empolgado para esse projeto.
